# .github/workflows/ci_docker_build.yml
name: Build and Push Container to GHCR

on:
  push:
    branches: [ "main" ]

env:
  # The image name format for GHCR is ghcr.io/OWNER/REPOSITORY
  IMAGE_NAME: devops-web-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Necessary permission to push to GHCR (GitHub Container Registry)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
        
    - name: Print image URL
      run: echo "Image pushed to ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"
